### ISSUE TITLE
Interfacing Sensors with Web Interface

### ISSUE THREAD

**Issue by jeffrobots** [ECESeniorDesign/greenhouse-webservice-demo#1]
As I've been able to get some sensor data acquisition working, we should start thinking about how we're going to integrate the sensor calls with the web frame database and how best to present that data.

I'm assuming you're going to want to poll sensor data periodically as well as on request. Do you want that to be handled by the web interface? Here's a few ideas on how to handle updating sensor data.

1) A background wrapper service that periodically (or on request) calls to the sensor scripts to update and store sensor data somewhere on the internet that the app will access.

2) The sensor scripts, when called, will update a local file containing data with which the web service interacts.

3) The python scripts directly return values into the wrapper, which will then do any necessary calculations and update values on the web as necessary

To me, it seems that the third option could be a decent way to go. We'll need to be careful with exception handling to make sure a sensor failure doesn't crash the entire platform though. If the sensor scripts run separately and update a shared memory location (as in 1 and 2), then a failed sensor will just mean the values stop updating but we don't need to handle an exception at all.

**Comment by cconklin** [comment]
I like option 3. Exception handling isn't scary.

**Comment by cconklin** [comment]
I have enough so that you should be able to interface with it. You are going to need to clone both this and lazy_record. Then, you can `import` the models file in this, and call `SensorDataPoint.record()` passing, the sensor kind (light, water, humidity, ...) and value (as a floating point), and which plant (1 or 2). You also need to connect the database (`import app` then call `lazy_record.connect_db(app.app.config['DATABASE'])`)

**Comment by cconklin** [comment]
You won't need to clone lazy_record anymore. Just `pip install` it.

**Comment by jeffrobots** [comment]
Just to clarify, I should be installing lazy_record0.1.1.dev from PyPi correct?

Is there any additional/specific configuration that needs to be done aside from cloning the webservice demo and installing lazy_record? Lazy_record is documented pretty well, so I think I can manage there so long as I know that the webservice is set up properly.

**Comment by cconklin** [comment]
There shouldn't be anything more. I can answer any questions on lazy_record. I'll probably push another development release in a week or so. I'll also be improving the docs for that release. If you make any changes to the greenhouse we service, please do so on a branch.

**Comment by cconklin** [comment]
Actually, ensure you have SQLite installed, and have created the database to the location specified in the app.py file. Then load the schema with 'sqlite < schema.sql'

**Comment by jeffrobots** [comment]
I'm having difficulty getting lazy_record to install. Any idea what could be preventing it? It shows up in the pip package listing and the log shows that it's finding the links, but it ignores them and says that there are "no versions that satisfy the requirement."

I'm assuming there would be a workaround if I cloned and went from there, but I'd much rather prefer to work off the the pip installer so that we're on the same page.

EDIT:
Scratch that. Running `sudo pip install <direct URL to package>` worked. No idea if this will update properly, as I shouldn't have needed to sudo pip from what I've read and it shouldn't have ignored the package lists, but I'll let you know if there are any issues with regards to that.

**Comment by cconklin** [comment]
That's odd. I've not tried installing it on a Pi, but I can `pip install lazy_record` without any issue. If you ever run into serious issues, you can always clone the repo, check out to a certain tag, then `pip install .` with the repo as the current directory.

**Comment by jeffrobots** [comment]
[As per a recent commit on greenhouse-sensors](https://github.com/ECESeniorDesign/greenhouse-sensors/commit/13c06d7a230f20efa5b15ccbbee2ae22d221d495):

Treating an individual plant's sensors as a cluster object that contains information on addresses, channels, and IDs is working as planned. I've committed a small script that demonstrates their use within the commit linked above. This script creates two plant sensor clusters and calls the necessary functions to update and report sensor information.

At this time, I haven't mixed in any of the database calls or updates, but that will be the next step - along with some hardware related tasks - now that the sensor cluster objects have been created.
